### ISSUE TITLE
FonzecaFleming misnamed

### ISSUE THREAD

**Issue by MLopez-Ibanez** [cog-imperial/entmoot#16]
The function should be called `FonsecaFleming` as it was proposed by Fonseca, C. M.; Fleming, P. J. (1995). "An Overview of Evolutionary Algorithms in Multiobjective Optimization". [Evol Comput](https://en.wikipedia.org/wiki/Evolutionary_Computation_(journal)). 3 (1): 1–16. doi:[10.1162/evco.1995.3.1.1](https://doi.org/10.1162%2Fevco.1995.3.1.1)

**Comment by R-M-Lee** [comment]
You are right of course - thank you. The benchmarks have changed and FonsecaFleming is not there any more so I am closing this

**Comment by R-M-Lee** [comment]
...or not, since I don't have the permission

**Comment by MLopez-Ibanez** [comment]
Happy to close for you then.
