### ISSUE TITLE
lightgbm model hyperparameter tuning

### ISSUE THREAD

**Issue by R-M-Lee** [cog-imperial/entmoot#19]
@spiralulam What do you think about giving Enting.fit a kwargs parameter to allow the user to set the lightgbm hyperparameters? I want to do something like cross-validation to get a better surrogate rather than accept the default.

Then we can either leave the choice of hyperparameters to the user or provide a simple function to optimize the hyperparams (I would propose random sampling in this case to keep things relatively simple).

**Comment by R-M-Lee** [comment]
update: ok I noticed that Enting takes a params dict and the hyperparameters are specified here:

`params["tree_train_params"]["train_params"]`

More generally, have we documented what can be in the params dict? I see unc_params and tree_training_params from going through the code but I'm not sure I would find this in the docs

**Comment by spiralulam** [comment]
@R-M-Lee Yes, we need to document the params dict. Will do.

**Comment by spiralulam** [comment]
You can now check all possible parameters using the new class structure implemented by Toby.
