### ISSUE TITLE
Make gurobipy import optional

### ISSUE THREAD

**Issue by marcosfelt** [cog-imperial/entmoot#3]
Currently, ENTMOOT requires GUROBIpy to be installed, though it should work without it. It would be great if gurobipy could be imported flexibly so that the package can be used without it.

**Comment by ThebTron** [comment]
Thanks @marcosfelt for the suggestion!  In the current implementation ENTMOOT will only try to import GUROBIpy if "global" is selected for "acq_optimizer". If you pick "sampling" as the optimization strategy instead there shouldn't be any GUROBIpy imports. Can you give more details on when exactly you're experiencing this issue? I might have left an unnecessary import of GUROBIpy in there.

**Comment by marcosfelt** [comment]
My bad, that was an issue with Summit.
