### ISSUE TITLE
Provide a simple Bayesian optimization loop example 

### ISSUE THREAD

**Issue by TobyBoyne** [cog-imperial/entmoot#34]
The documentation currently doesn't include an example for how to do a complete Bayesian optimization loop with ENTMOOT, only a single iteration. I think we should provide an example of a complete loop for clarity, or at least tidy up the notebook below and include it in the readthedocs.

https://github.com/cog-imperial/entmoot/blob/master/docs/notebooks/single_obj_hyperparam_opt_localgurobi.ipynb

**Comment by spiralulam** [comment]
Hi Toby, that is a very good idea. Would you mind providing an example?
